training:
  ENV_NAME: multiquad_ix4
  ENV_KWARGS:
    reward_coeffs:
      distance_reward_coef: 1.0
      velocity_reward_coef: 1.0
      safe_distance_coef: 1.0
      up_reward_coef: 1.0
      linvel_reward_coef: 1.0
      ang_vel_reward_coef: 0.0
      linvel_quad_reward_coef: 1.0
      taut_reward_coef: 1.0
      collision_penalty_coef: -10.0
      out_of_bounds_penalty_coef: -10.0
      smooth_action_coef: -1.0
      action_energy_coef: -1.0
    obs_noise: 0.0
    act_noise: 0.0
    max_thrust_range: 0.2
    num_quads: 2
    episode_length: 2048
    cable_length: 0.4
    payload_mass: 0.01
    policy_freq: 250
  TOTAL_TIMESTEPS: 1000000
  NUM_ENVS: 16384
  NUM_STEPS: 64
  NUM_MINIBATCHES: 128
  UPDATE_EPOCHS: 8
  ANNEAL_LR: false
  LR: 0.0004
  ACTIVATION: tanh
  MAX_GRAD_NORM: 0.5
  CLIP_EPS: 0.2
  VF_COEF: 0.5
  ENT_COEF: 0.01
  GAMMA: 0.995
  GAE_LAMBDA: 0.95
  SEED: 0
  ACTOR_ARCH:
    - 64
    - 64
    - 64
  CRITIC_ARCH:
    - 128
    - 128
    - 128
  DISABLE_JIT: false
  PROJECT: crazymarl
  NAME: quad_marl
  WANDB_MODE: online
