training:
  ENV_KWARGS:
    max_thrust_range: 0.15
    num_quads: 1
    cable_length: 0.3
    payload_mass: 0.01
    payload: false  # Set to False for no payload
    reward_coeffs:
      distance_reward_coef: 1.0
      velocity_reward_coef: 1.0
      safe_distance_coef: 1.0
      up_reward_coef: 1.0
      linvel_reward_coef: 1.0
      ang_vel_reward_coef: 1.0
      linvel_quad_reward_coef: 1.0
      taut_reward_coef: 1.0
      collision_penalty_coef: -10.0
      out_of_bounds_penalty_coef: -10.0
      smooth_action_coef: -50.0
      action_energy_coef: -1.0
  TOTAL_TIMESTEPS: 350000000
  NUM_ENVS: 16384
  NUM_STEPS: 64
  
