training:
  ENV_KWARGS:
    max_thrust_range: 0.15
    num_quads: 6
    cable_length: 0.45
    payload_mass: 0.04
  TOTAL_TIMESTEPS: 5000000000
  ACTOR_ARCH:
    - 256
    - 64
    - 64
  CRITIC_ARCH:
    - 256
    - 128
    - 128
